import 'dart:io';
import 'package:flutter/material.dart';
import 'package:smartcityfeedbacksystem/models/feedback_model.dart';
import 'package:smartcityfeedbacksystem/provider/auth_provider.dart';
import 'package:smartcityfeedbacksystem/services/services.dart';
import 'package:smartcityfeedbacksystem/utils/image_picker.dart';
import 'package:smartcityfeedbacksystem/utils/snack_bar.dart';
import 'package:smartcityfeedbacksystem/widgets/custom_button.dart';
import 'package:provider/provider.dart';

class AddFeedbackScreen extends StatefulWidget {
  @override
  _AddFeedbackScreenState createState() => _AddFeedbackScreenState();
}

class _AddFeedbackScreenState extends State<AddFeedbackScreen> {
  File? _image;
  final TextEditingController _titleController = TextEditingController();
  final TextEditingController _problemController = TextEditingController();

  @override
  void dispose() {
    _titleController.dispose();
    _problemController.dispose();
    super.dispose();
  }

  void _selectImage() async {
    File? pickedImage = await pickImage(context);
    if (pickedImage != null) {
      setState(() {
        _image = pickedImage;
      });
    }
  }

  Future<void> _saveFeedback(BuildContext context) async {
    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final feedbackService = FeedbackService();

    if (_image == null) {
      showSnackBar(context, 'Please select an image for the feedback.');
      return;
    }

    String userId = authProvider.uid;
    String title = _titleController.text.trim();
    String problemFaced = _problemController.text.trim();

    if (title.isEmpty || problemFaced.isEmpty) {
      showSnackBar(context, 'Please fill in all fields.');
      return;
    }

    FeedbackModel feedback = FeedbackModel(
      id: '', // Placeholder value, will be generated by Firestore
      userId: userId,
      title: title,
      problemFaced: problemFaced,
      imagePath: '',
      upvotes: 0,
      downvotes: 0,
      comments: [],
    );

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return Dialog(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                CircularProgressIndicator(),
                SizedBox(width: 16.0),
                Text('Saving feedback...'),
              ],
            ),
          ),
        );
      },
    );

    try {
      String feedbackId = await feedbackService.createFeedback(feedback);

      String imagePath =
          await feedbackService.storeImage(feedbackId, _image!);

      feedback.imagePath = imagePath;
      feedback.id = feedbackId; // Update the feedback's ID with the generated ID

      await feedbackService.updateFeedback(feedback);

      Navigator.pop(context); // Close the saving feedback dialog

      showSnackBar(context, 'Feedback saved successfully.');

      Navigator.pop(context); // Close the Add Feedback screen
    } catch (e) {
      Navigator.pop(context); // Close the saving feedback dialog
      showSnackBar(context, 'Failed to save feedback. Please try again.');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Add Feedback'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            GestureDetector(
              onTap: _selectImage,
              child: _image == null
                  ? CircleAvatar(
                      backgroundColor: Colors.grey,
                      radius: 50,
                      child: Icon(
                        Icons.image,
                        size: 50,
                        color: Colors.white,
                      ),
                    )
                  : CircleAvatar(
                      backgroundImage: FileImage(_image!),
                      radius: 50,
                    ),
            ),
            SizedBox(height: 16.0),
            TextField(
              controller: _titleController,
              decoration: InputDecoration(
                labelText: 'Title',
              ),
            ),
            SizedBox(height: 16.0),
            TextField(
              controller: _problemController,
              decoration: InputDecoration(
                labelText: 'Problem Faced',
              ),
            ),
            SizedBox(height: 16.0),
            CustomButton(
              text: 'Save Feedback',
              onPressed: () => _saveFeedback(context),
            ),
          ],
        ),
      ),
    );
  }
}
